import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import React from "react";
import Footer from "@/app/components/Footer";
import { ToastProvider } from "@/app/contexts/ToastContext";
import { SellerNavProvider } from "@/app/contexts/SellerNavContext";
import SellerSidebar from "@/app/components/seller/SellerSidebar";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin", "vietnamese"],
  display: "swap",
});

const mono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin", "vietnamese"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "CycleX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${mono.variable} font-sans antialiased`}
      >
        <ToastProvider>
          <SellerNavProvider>
            <div className="min-h-screen flex flex-col w-full overflow-x-hidden">
              <Header />
              <SellerSidebar />
              <main className="flex-1 w-full">{children}</main>
              <Footer />
            </div>
          </SellerNavProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
